version: '3'
services:
  my_postgres:
    image: postgres:latest
    container_name: auth
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    volumes:
        - ./postgres-data:/var/lib/postgresql/data

