version: '3'
services:
  my_postgres:
    image: postgres:latest
    container_name: auth
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
  minio:
    image: bitnami/minio
    container_name: chat
    restart: unless-stopped
    volumes:
      - minio:/data
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniosecret
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
    minio:
      driver: local
    pgdata:
      driver: local
